### PR TITLE
Add console support to SimpleStaffChat2

### PR DESCRIPTION
**Pull request by MegaTophat**
Adds the ability to see staffchat messages and send them from the console.

### CODE REVIEW

**Comment by Refrac** [comment]
@MegaTophat Why did you close and delete it?

**Comment by MegaTophat** [comment]
Because I realized I am retarded and forgot to do the spigot side of things lol. I'm working on it now

**Comment by Refrac** [comment]
> Because I realized I am retarded and forgot to do the spigot side of things lol. I'm working on it now

Ah well you didn't need to delete the repo for that lol, you still need a fork to open a pull request

**Comment by MegaTophat** [comment]
Yeah I definitely did not do the right thing there lol. I'm still new to this so my b...

**Comment by Refrac** [comment]
I actually added support for console except for join messages on spigot already

**Comment by MegaTophat** [comment]
I'll just do it rq then lol

**Comment by MegaTophat** [comment]
I am noticing there is stuff in here like that already. Sending staffchat from console definitely wasn't possible though since you returned immediately if the sender wasn't an instance of a Player right at the top of StaffChatCommand.

**Comment by Refrac** [comment]
Ah i forgot to add console sending for it currently just logs the messages to console

**Comment by MegaTophat** [comment]
Also I noticed with the placeholder boolean and PlaceholderAPI, is there a way to use the ConsoleSender as the player? If not then messages being logged where the console is the sender will not properly use placeholders from PlaceholderAPI

**Comment by Refrac** [comment]
> Also I noticed with the placeholder boolean and PlaceholderAPI, is there a way to use the ConsoleSender as the player? If not then messages being logged where the console is the sender will not properly use placeholders from PlaceholderAPI

I don't think PlaceholderAPI supports sending placeholders as a ConsoleSender

**Comment by MegaTophat** [comment]
Ok. The only thing I can figure out is that if you use a placeholder, when the message getting sent is from the console, everyone will just see the placeholder itself if it's a placeholderapi placeholder. The only fix I can think is having a different message format for each message that can be sent from the console's perspective, which would also allow people to completely change the name of the console in the message. Does that sound like an idea that would work from you.

**Comment by Refrac** [comment]
> Ok. The only thing I can figure out is that if you use a placeholder, when the message getting sent is from the console, everyone will just see the placeholder itself if it's a placeholderapi placeholder. The only fix I can think is having a different message format for each message that can be sent from the console's perspective, which would also allow people to completely change the name of the console in the message. Does that sound like an idea that would work for you?

Ya sure sounds good

**Pull request closed without merging**
