### PR TITLE
Console Support

### PR DESCRIPTION
**Pull request by MegaTophat**
Add console support to send staffchat messages from the console, as well as receive join, leave, and switch messages from in game in the console.

### CODE REVIEW

**Comment by MegaTophat** [comment]
Ok hopefully this time I didn't forget anything... ;)

**Comment by Refrac** [comment]
Looks good so far i'll test these changes later

**Comment by MegaTophat** [comment]
I should note that I have tested these on 1.18.1 with Java 17 on the most recent Paper and Waterfall versions. If something doesn't work on 1.8/Java 8 lmk and I'll try to fix it.

**Comment by Refrac** [comment]
Works on 1.8.8/Java 8 merging. Thanks!

**Pull request merged**
